bdd_dbt:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'database'
      schema: 'main'
      schemas_and_paths:
        main: '/Users/dimitris/VSCode/bdd-dbt/mydata_db.db'
      schema_directory: '/Users/dimitris/VSCode/bdd-dbt'